[package]
edition = "2018"
name = "svd2rust-regress"
version = "0.1.0"
authors = ["James Munns <james.munns@gmail.com>", "The svd2rust developers"]

[dependencies]
reqwest = { version = "0.10", features= ["blocking"] }
rayon = "1.4"
structopt = "0.2"
error-chain = "0.12"
inflections = "1.1"
