dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=svd2rust
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  include:
    # Nightly, for testing
    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Atmel

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Freescale

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Fujitsu

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Holtek

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Nordic

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Nuvoton

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=NXP

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=SiliconLabs

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Spansion

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=STMicro

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=Toshiba

    # - env: TARGET=x86_64-unknown-linux-gnu VENDOR=OTHER
    #   rust: nightly

    # # Linux
    # - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=i686-unknown-linux-musl
    # - env: TARGET=x86_64-unknown-linux-gnu
    # - env: TARGET=x86_64-unknown-linux-musl

    # # OSX
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: AohBNo0QBsXxxyHcmElV1lZ0TCz83ul/woA9OKOiK07fbcwMnG9XI5HFkQAj/gOdL/O6N8R7EqRjwyc39VSJ0YsX9cyKfrUWoFgTBjySFOfKTG8Fh2WRMhnJUYfocjW8QnVAkPY0KDaVMnyDzl35+Ak/QqbOKXCO6nvfYIBmEhaW6yuYJjnkNpsn3wF3VfDA7XjkMe+24oWe6AYC7aH/CM1qws5+/6kp6VJr1xTkzH+zgNwJNXWmuDWCrMDreYamDwZ4mb0xlWd22I36ZAYDZMe8vIS7Bzw3bIlp0r4li5kDmIFQD39ft7jdNmGxDMFsuSVAyZOvvjfWP4axXncJLvXS1ygCMW9XR7gy3pTg/JXzcj9rnldntHLb2vIcwsXfcy78a7O+N+F9CjrcAeLUCBO43bqrFuX1RKtqicLzEi1IZoj6qYVcVbucyrOKU1ABgnemMT+ukizKjHbK2n8YPq6REUw4kr7aLySFRtb/Y/oSruXe1Ne0/698ty4OPHA+cyYkuPP3Q+Gw+26WKWetzLum1ZwvPlHxb3sdYvE6/38n0jPL/zszZoX88K8wjTDoKZZSse+CB4iXIigV8u3wSrPsuGHwBiG2DNmeITcvmU4g6xHkhXhD4RVbdrD4XGGQuMATXN+yKDg2ggkqxqkJZ/JnL3VjoBM8SdeVdj/zwnQ=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - staging
    - trying
    # release tags
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
