[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "svd2rust"
version = "0.1.0"

[dependencies]
clap = "2.14.0"
inflections = "1.0.0"
quote = "0.3.3"
svd-parser = "0.1.1"
syn = "0.9"
