[package]
edition = "2018"
authors = [
    "The ToolsTeam <tools@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
build = "build.rs"
categories = [
    "command-line-utilities",
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Generate Rust register maps (`struct`s) from SVD files"
documentation = "https://docs.rs/svd2rust"
keywords = [
    "arm",
    "cortex-m",
    "riscv",
    "msp430",
    "register",
    "map",
    "generator",
]
license = "MIT OR Apache-2.0"
name = "svd2rust"
repository = "https://github.com/rust-embedded/svd2rust/"
version = "0.15.1"
readme = "README.md"

[[bin]]
doc = false
name = "svd2rust"
path = "src/main.rs"

[dependencies]
cast = "0.2.2"
clap = "2.26.0"
env_logger = "~0.5"
error-chain = "0.11.0"
inflections = "1.1.0"
log = { version = "~0.4", features = ["std"] }
quote = "0.3.15"
svd-parser = "0.7"
syn = "0.11.11"
